name: rick_and_morty_api
description: Api manager https://rickandmortyapi.com/documentation/
version: 1.0.0
homepage: https://github.com/ingego/Dart-RickAndMorty

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  dio: ^4.0.6
  beautiful_soup_dart: ^0.3.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
